steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-saas-mcp'
      - '-f'
      - Dockerfile
      - .
images:
  - 'gcr.io/$PROJECT_ID/ai-saas-mcp'
